---
title: "MA plot"
author: "Gabriel Clérempuy"
date: "2023-11-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)
data <- read.csv("GSE139659_IPvsctrl.complete.csv", header = TRUE, sep = ";")

```
```{r}
head(data)
```


```{r}
#Création des colonnes : baseMean, log2FoldChange, pvalue
data$BaseMean <- (data$ctrl4 + data$ctrl5 + data$ctrl6 + data$IP1 + data$IP2 + data$IP3)/6
data$log2Foldchange <- log2((data$IP1 + data$IP2 + data$IP3) / (data$ctrl4 + data$ctrl5 + data$ctrl6))
head(data,100)

```
```{r}
#Tracer du MA-plot of complete RNA-seq dataset
data$log2FoldChange[data$log2FoldChange > 4] <- 4.1
data$log2FoldChange[data$log2FoldChange < -4] <- -4.1

png("MA_plot.png", width = 1050, height = 850)

plot(data$baseMean, data$log2FoldChange, 
     xlab = "Average Intensity (A)",
     ylab = "Log2 Fold Change (M)", 
     main = "MA-plot of complete RNA-seq dataset", 
     ylim = c(-4.5, 4.5),
     log = "x",
     cex = 1)

#coloration des points selon leur p-value
points(data$baseMean, data$log2FoldChange,cex = 1, pch = 19, col = ifelse(data$pvalue < 0.05, "red", "black"))

#Mise en forme de triangle les données supérieur à 4 et inférieur à -4 et coloration en rouge(vérifié au préalable)
points(data$baseMean[data$log2FoldChange > 4], data$log2FoldChange[data$log2FoldChange > 4], pch = 24, cex = 1, col = "red")
points(data$baseMean[data$log2FoldChange < -4], data$log2FoldChange[data$log2FoldChange < -4], pch = 25, cex = 1, col = "red")


abline(h = 0, col = "black", lty = 2)
dev.off()


```
```{r}
#Tracer du MA-plot of complete RNA-seq dataset

data <- read.csv("GSE139659_IPvsctrl.complete.csv", header = TRUE, sep = ";")

png("MA-plot of genes related to translation.png", width = 1000, height = 1000)

plot(log2(data$baseMean), data$log2FoldChange, 
     xlab = "log2 BaseMean",
     ylab = "Log2 Fold Change (M)", 
     main = "MA-plot of genes related to translation", 
     ylim = c(-6, 5),
     xlim = c(0,20),
     cex = 1)

#coloration des points selon leur p-value
points(data$baseMean, data$log2FoldChange,cex = 1, pch = 19, col = ifelse(data$pvalue < 0.05, "red", "black"))

abline(h = 0, col = "black", lty = 2)

# Personnalisez les étiquettes de l'axe des x pour qu'elles aillent de deux en deux
axis(1, at = seq(0, 20, by = 2))

# Personnalisez les étiquettes de l'axe des y pour afficher toutes les valeurs
axis(2, at = seq(-6, 5, by = 1))

```

